base_url = "https://tamimehsan.github.io/clings/"
title = "Clings"
description = "Small exercises to get you used to reading and writing Rust code!"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "dracula"

insert_anchor_links = "heading"

[extra]
logo_path = "images/happy_ferris.svg"

[[extra.menu_items]]
name = "Clings"
url = "@/_index.md"
[[extra.menu_items]]
name = "Setup"
url = "@/setup/index.md"
[[extra.menu_items]]
name = "Usage"
url = "@/usage/index.md"
[[extra.menu_items]]
name = "Community Exercises"
url = "@/community-exercises/index.md"
[[extra.menu_items]]
name = "Q&A"
url = "https://github.com/tamimehsan/clings/discussions/categories/q-a?discussions_q="

[[extra.footer_items]]
name = "Repository"
url = "https://github.com/tamimehsan/clings"
[[extra.footer_items]]
name = "Changelog"
url = "https://github.com/tamimehsan/clings/blob/main/CHANGELOG.md"
[[extra.footer_items]]
name = "MIT License"
url = "https://github.com/tamimehsan/clings/blob/main/LICENSE"
